### PR TITLE
Update AuthenticatorManager.java

### PR DESCRIPTION
**Pull request by The28AWG**
removed the dependence on Activity.

### CODE REVIEW

**Comment by alinhayati** [comment]
Eliminating `Activity activity` in the constructor is not correct, since it is the calling activity and differs from the `RegistrationActivity`.

**Comment by The28AWG** [comment]
Hello!
It's wrong.
Need work "Add account" in "Settings -> Accounts".
It's not OAuth technology, its android account synchronize mechanism.
https://developer.android.com/reference/android/accounts/AccountManager.html

> This class provides access to a centralized registry of the user's online accounts. The user enters credentials (username and password) once per account, granting applications access to online resources with "one-click" approval.

**Comment by alinhayati** [comment]
Hi,
Adding account can be done in two ways, from Settings and the App itself. Thus, the method shall fit the two scenarios. In the latter case, there is another Activity in the App which calls RegistrationActivity for registration. This does not infringe OAuth, and it is the authentication mechanism used by Android and here.

**Comment by The28AWG** [comment]
I added 2 methods:

``` java
     public void getAccessToken(String accountName, String authTokenType, Bundle options) {
         getAccessToken(accountName, authTokenType, options, null);
     }

     public void getAccessToken(String accountName, String authTokenType, Bundle options, Activity activity) {
....
}
```

and:

``` java
public void addAccount(String authTokenType, String[] requiredFeatures, Bundle options) {
        addAccount(authTokenType, requiredFeatures, options, null);
    }

    public void addAccount(String authTokenType, String[] requiredFeatures, Bundle options, Activity activity) {
....
}
```

If need Activity use addAccount(authTokenType, requiredFeatures, options, activity);

**Comment by The28AWG** [comment]
If create account in Settings then app crashes. First need initialize AuthenticatorManager.

**Comment by alinhayati** [comment]
You have removed `callingActivity` from `AuthenticatorManager` constructor and you can not call its non-static `addAccount` method overloaded with Activity in this way.
The app also works flawlessly in adding account from Settings and inside App. I double checked it. If you encountered any problem please detail.

**Comment by The28AWG** [comment]
@alinhayati ok. =(
I commited my modifications. Me need single account authentificator for many apps. You have good idea and bad realization.
Need pre initialize interface and authenticator implementations.

``` java
    private void saveClassNamesInSharedPref(String registrationActivityName, String interfaceImplementationClassName) {
        SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context);
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putString(AuthenticatorManager.KEY_REGISTRATION_ACTIVITY_CLASS_NAME, registrationActivityName);
        editor.putString(AuthenticatorManager.KEY_INTERFACE_IMPLEMENTATION_CLASS_NAME, interfaceImplementationClassName);
        editor.commit();
    }
```

If not call this method at least once you app crashed. Because it will apply the default values.

**Pull request closed without merging**
